version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Run tests
          command: flutter test
      - run:
          name: Create dir for test_results
          command: mkdir test_results
      - run:
          name: Build the Android version
          command: flutter build apk
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
      - store_test_results:
          path: test_results
